* Maze Nodes
** Start (0)
All players are missing items that don't pertain to their secrets, they are all bound in ropes individually, arranged in a circle around a single knife. 
The scene is lit by a gentle blue glow from the ceiling, scrape marks appear on the side walls.
*** Wolves: Require Perception Roll for this!
- Two sleeping wolves are chained on opposing walls, with a blank wall South and a wooden door North
- Any noise speaking or louder will wake these wolves, they struggle against their chains to reach the party (ST 12, two successes breaks the chain from the wall)
- The wolves are visibly starving
- The rocks they're chained to appear to be new (only note if someone is particularly perceptive/looking)
- They have 5 HP each and will attack with bites (skill 12, 1d damage on hit)
*** If players take too long
- The back wall begins to move forward, but allow easy escape through door (it's unlocked and opens outwards)
*** Exits
Just First Hall

** First Hall 
The hall stands three-people wide. It is made of carved stone with moss covering most edges between tiles. Torches stand in shiny new racks every ten yards or so.
This continues for 120 yards, ending at a T-shaped fork with the flat side to the North. The flat side has a stone plaque with ancient writing upon it.
- The engraving appears as though it's been touched up recently, but remains in its original stone
- Three keys are engraved below the writing
- Vertical lines separate the writing from glyphs to each side
- A spiral adorns the right, a beetle the left
- Both directions lead to a passage that sharply turns northward within sight
*** If Earl Prestio is in the party (roll knowledge to decide clarity of translation)
The plaque says

#+BEGIN_QUOTE
Heroes are required for the end of days.
You've been chosen for the test.
Escape to choose your fate.
#+END_QUOTE

In the recognized culture:
- Beetles indicate a temporary task or minor journey
- Spirals symbolize fate
- Any ordered process goes left to right from the entrance, even in the architecture
*** If Max Myrmood is in the party
The writing looks like the stuff a doomsday cult he's tussled with tattoos on their faces.
*** If Grumble is in the party and talks to the moss
There has been lots of traffic lately, after generations of rest. One very large presence and dozens of smaller ones.
*** Exits
- Left: Junk Room
- Right: Second Fork

** Junk Room
A few yards after the Northward turn, the hallway opens West into a large room filled with all manner of rusty and broken objects.
*** Beside the opening
There's an engraved stone plaque with three glyphs resembling keys upon it, the leftmost is circled
*** In the room
There is no decomposable junk left, but some charcoal dust can be found in some of the spaces between heaps.
- Improvised weapons can be found, but roll for pile stability if players uncareful (pile tumbles towards grabber on rolls of 10+, dodge or take 1d-3 damage)
- A successful scrounging roll can procure a "like new" item/weapon, but failure results in 1d-3 damage
- In one corner, the tallest pile's top rests a few feet below a key hanging on a hook from the ceiling
- Climbing-4 to top the mound accident-free
- Failure by 2 or less results in half-way progress due to the shifting pile
- Failure by 3 or more results in 1d-3 damage and a lack of progress

