* Maze Nodes
** Start (0)
All players are missing items that don't pertain to their secrets, they are all bound in ropes individually, arranged in a circle around a single knife. 
The scene is lit by a gentle blue glow from the ceiling, scrape marks appear on the side walls.
*** Wolves: Require Perception Roll for this!
- Two sleeping wolves are chained on opposing walls, with a blank wall South and a wooden door North
- Any noise speaking or louder will wake these wolves, they struggle against their chains to reach the party (ST 12, two successes breaks the chain from the wall)
- The wolves are visibly starving
- The rocks they're chained to appear to be new (only note if someone is particularly perceptive/looking)
- They have 5 HP each and will attack with bites (skill 12, 1d damage on hit)
*** If players take too long
- The back wall begins to move forward, but allow easy escape through door (it's unlocked and opens outwards)
*** Exits
Just First Hall

** First Hall 
The hall stands three-people wide. It is made of carved stone with moss covering most edges between tiles. Torches stand in shiny new racks every ten yards or so.
This continues for 120 yards, ending at a T-shaped fork with the flat side to the North. The flat side has a stone plaque with ancient writing upon it.
- The engraving appears as though it's been touched up recently, but remains in its original stone
- Three keys are engraved below the writing
- Vertical lines separate the writing from glyphs to each side
- A spiral adorns the right, a beetle the left
- Both directions lead to a passage that sharply turns northward within sight
*** If Earl Prestio is in the party (roll knowledge to decide clarity of translation)
The plaque says

#+BEGIN_QUOTE
Heroes are required for the end of days.
You've been chosen for the test.
Escape to choose your fate.
#+END_QUOTE

In the recognized culture:
- Beetles indicate a temporary task or minor journey
- Spirals symbolize fate
- Any ordered process goes left to right from the entrance, even in the architecture
*** If Max Myrmood is in the party
The writing looks like the stuff a doomsday cult he's tussled with tattoos on their faces.
*** If Grumble is in the party and talks to the moss
There has been lots of traffic lately, after generations of rest. One very large presence and dozens of smaller ones.
*** Exits
- Left: Junk Room
- Right: Second Fork

** Junk Room
A few yards after the Northward turn, the hallway opens West into a large room filled with all manner of rusty and broken objects.
*** Beside the opening
There's an engraved stone plaque with three glyphs resembling keys upon it, the leftmost is circled
*** In the room
There is no decomposable junk left, but some charcoal dust can be found in some of the spaces between heaps.
- Improvised weapons can be found, but the junk is dangerous and unstable (Scrounging):
   + If no scrounging skill, defaults to Perception-4, Observation-2, or Appraisal-2
   + On any failure 1d-3 damage, but a rusty/broken item is found
   + On success by less than 4, a rusty/broken item is found safely
   + On success by 4 or more, a "like new" item is found
- In one corner, the tallest pile's top rests a few feet below a key hanging on a hook from the ceiling
- Climbing-4 to top the mound accident-free
- Failure by 2 or less results in half-way progress due to the shifting pile
- Failure by 3 or more results in 1d-3 damage and a lack of progress

** Second Fork
The path splits once more with a plaque, writing, beetle to the left, spiral to the right, two keys on the bottom.
*** If Earl Prestio is in the party (roll knowledge to decide clarity of translation)
The plaque says

#+BEGIN_QUOTE
Conquer your fear, conquer the pack.
Conquer your fear, conquer the fire.
Conquer your fear, conquer your self.
Escape to choose your fate.
#+END_QUOTE

*** Exits
- Left: Wolf Den
- Right: Fire gauntlet

** Wolf Den
As you walk along this path, you begin to smell mint, lavender, and death. A turn leads to a decomposing corpse missing a leg. 
The corpse is unrecognizable, but carries a rusty sword in its outstretched left hand.
A trail of dried blood smears through a floor section of the hall covered in wreaths of dried lavender and mint on all sides.
Beyond lies a dark cave with the sound of multiple snoring beasts within.
*** GM Note
- The wolves are trained to avoid lavender and mint, that's what holds them in the cave. 
- The wreaths are covered in an itchy white powder that can be seen upon close inspection (or passive Per-4 success)
- Will rolls are required not to drop the foliage and itch if handled with bare skin
- Itching will persist and reattack at each stressful event for the rest of the game (Will to resist, DX-2 for 30 seconds on failure)
- The players will probably try to weaponize this, allow it, but make them careful not to touch the weapon with bare skin
*** In the cave
- Four wolves, sleeping and identical to the two at the start, but unchained
- Beneath a blue glow in the back, the key
- If sneaking, wolves have a perception of 12 and a penalty while sleeping of -4

